from . import industry_examples
from . import asset
from . import category
from . import location
from . import issue_order
from . import asset_request
from . import reservation
from . import res_config_settings
from . import purchase_request
from . import purchase_extension
from . import service_contract
from . import warranty_claim
from . import maintenance_team
from . import maintenance_checklist
from . import maintenance_order
from . import maintenance_schedule
from . import technician_skill
from . import res_company
from . import agreement
from . import product_template
from . import service_equipment
from . import order_equipment
from . import sale_order
from . import project_task
from . import stock_picking
from . import dashboard
